In [1]:
# 데이터 불러오기
import pandas as pd

file_path = "/content/drive/MyDrive/JeonseGuard/실거래가/전월세/연립다세대/202504_연립다세대_전세_실거래가.csv" # CSV 파일 경로 지정
df = pd.read_csv(file_path, encoding='cp949') # CP949 인코딩

In [2]:
# 상위 5개 확인
df.head()

,NO,시군구,번지,본번,부번,건물명,전월세구분,전용면적(㎡),계약년월,계약일,...,월세금(만원),층,건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,1,서울특별시 강서구 화곡동,105-121,105,121,하이트맨션,월세,66.99,202504,30,...,30,-1,1999,까치산로4가길 48,202507~202707,신규,-,NaN,NaN,다세대
1,2,서울특별시 서초구 방배동,900-4,900,4,(900-4),월세,32.67,202504,30,...,5,3,2015,방배로20길 25-22,202506~202706,갱신,-,"23,100",0.0,다세대
2,3,인천광역시 서구 석남동,481-2,481,2,태성빌라(481-2),전세,39.92,202504,30,...,0,4,1993,명가골로8번길 1,202505~202705,신규,-,NaN,NaN,다세대
3,4,서울특별시 서대문구 홍은동,199-1,199,1,그랜드파크,전세,58.34,202504,30,...,0,2,1990,연희로41가길 21,202504~202703,갱신,-,"19,000",0.0,연립
4,5,서울특별시 서대문구 북가좌동,382-1,382,1,동하빌라,전세,63.06,202504,30,...,0,3,2001,수색로8가길 21,202504~202704,신규,-,NaN,NaN,다세대

In [3]:
# 컬럼명 확인
print(df.columns)

Index(['NO', '시군구', '번지', '본번', '부번', '건물명', '전월세구분', '전용면적(㎡)', '계약년월', '계약일',
       '보증금(만원)', '월세금(만원)', '층', '건축년도', '도로명', '계약기간', '계약구분', '갱신요구권 사용',
       '종전계약 보증금(만원)', '종전계약 월세(만원)', '주택유형'],
      dtype='object')

In [4]:
# 특정 컬럼 값만 확인
df["보증금(만원)"].head()

0    12,000
1    23,100
2     6,700
3    17,000
4    22,000
Name: 보증금(만원), dtype: object

In [5]:
# 전세만 필터링
jeonse_df = df[df["전월세구분"] == "전세"]
jeonse_df.head()

,NO,시군구,번지,본번,부번,건물명,전월세구분,전용면적(㎡),계약년월,계약일,...,월세금(만원),층,건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
2,3,인천광역시 서구 석남동,481-2,481,2,태성빌라(481-2),전세,39.92,202504,30,...,0,4,1993,명가골로8번길 1,202505~202705,신규,-,NaN,NaN,다세대
3,4,서울특별시 서대문구 홍은동,199-1,199,1,그랜드파크,전세,58.34,202504,30,...,0,2,1990,연희로41가길 21,202504~202703,갱신,-,"19,000",0.0,연립
4,5,서울특별시 서대문구 북가좌동,382-1,382,1,동하빌라,전세,63.06,202504,30,...,0,3,2001,수색로8가길 21,202504~202704,신규,-,NaN,NaN,다세대
6,7,서울특별시 강남구 개포동,1205-3,1205,3,효성럭스빌,전세,69.22,202504,30,...,0,4,2003,개포로26길 24,202505~202705,신규,-,NaN,NaN,다세대
7,8,인천광역시 미추홀구 주안동,631-6,631,6,청도벨리,전세,35.94,202504,30,...,0,3,2002,한나루로563번길 14-22,202505~202705,신규,-,NaN,NaN,연립다세대

In [6]:
# 신규만 필터링
jeonse_df = df[df["계약구분"] == "신규"]
jeonse_df.head()

,NO,시군구,번지,본번,부번,건물명,전월세구분,전용면적(㎡),계약년월,계약일,...,월세금(만원),층,건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,1,서울특별시 강서구 화곡동,105-121,105,121,하이트맨션,월세,66.99,202504,30,...,30,-1,1999,까치산로4가길 48,202507~202707,신규,-,NaN,NaN,다세대
2,3,인천광역시 서구 석남동,481-2,481,2,태성빌라(481-2),전세,39.92,202504,30,...,0,4,1993,명가골로8번길 1,202505~202705,신규,-,NaN,NaN,다세대
4,5,서울특별시 서대문구 북가좌동,382-1,382,1,동하빌라,전세,63.06,202504,30,...,0,3,2001,수색로8가길 21,202504~202704,신규,-,NaN,NaN,다세대
6,7,서울특별시 강남구 개포동,1205-3,1205,3,효성럭스빌,전세,69.22,202504,30,...,0,4,2003,개포로26길 24,202505~202705,신규,-,NaN,NaN,다세대
7,8,인천광역시 미추홀구 주안동,631-6,631,6,청도벨리,전세,35.94,202504,30,...,0,3,2002,한나루로563번길 14-22,202505~202705,신규,-,NaN,NaN,연립다세대

In [7]:
# 변경 매핑 딕셔너리 정의
renamed_columns = {
    "시군구": "address",
    "본번": "bun",
    "부번": "ji",
    "층": "floor",
    "전용면적(㎡)": "area",
    "전월세구분": "rent_type",
    "계약구분": "contract_type",
    "계약년월": "contract_year_month",
    "보증금(만원)": "price",
    "주택유형": "housing_type"
}

In [8]:
# 매핑에 해당하는 컬럼만 필터링
df = df.rename(columns=renamed_columns)
changed_df = df[list(renamed_columns.values())]
changed_df.head()

,address,bun,ji,floor,area,rent_type,contract_type,contract_year_month,price,housing_type
0,서울특별시 강서구 화곡동,105,121,-1,66.99,월세,신규,202504,"12,000",다세대
1,서울특별시 서초구 방배동,900,4,3,32.67,월세,갱신,202504,"23,100",다세대
2,인천광역시 서구 석남동,481,2,4,39.92,전세,신규,202504,"6,700",다세대
3,서울특별시 서대문구 홍은동,199,1,2,58.34,전세,갱신,202504,"17,000",연립
4,서울특별시 서대문구 북가좌동,382,1,3,63.06,전세,신규,202504,"22,000",다세대

In [9]:
# rent_type 컬럼에서 "전세"만 필터링
jeonse_df = changed_df[changed_df["rent_type"] == "전세"].reset_index(drop=True)
jeonse_df.head()

,address,bun,ji,floor,area,rent_type,contract_type,contract_year_month,price,housing_type
0,인천광역시 서구 석남동,481,2,4,39.92,전세,신규,202504,"6,700",다세대
1,서울특별시 서대문구 홍은동,199,1,2,58.34,전세,갱신,202504,"17,000",연립
2,서울특별시 서대문구 북가좌동,382,1,3,63.06,전세,신규,202504,"22,000",다세대
3,서울특별시 강남구 개포동,1205,3,4,69.22,전세,신규,202504,"42,500",다세대
4,인천광역시 미추홀구 주안동,631,6,3,35.94,전세,신규,202504,"5,600",연립다세대

In [10]:
# contract_type 컬럼에서 "신규"만 필터링
jeonse_df = jeonse_df[jeonse_df["contract_type"] == "신규"].reset_index(drop=True)
jeonse_df.head()

,address,bun,ji,floor,area,rent_type,contract_type,contract_year_month,price,housing_type
0,인천광역시 서구 석남동,481,2,4,39.92,전세,신규,202504,"6,700",다세대
1,서울특별시 서대문구 북가좌동,382,1,3,63.06,전세,신규,202504,"22,000",다세대
2,서울특별시 강남구 개포동,1205,3,4,69.22,전세,신규,202504,"42,500",다세대
3,인천광역시 미추홀구 주안동,631,6,3,35.94,전세,신규,202504,"5,600",연립다세대
4,서울특별시 중랑구 중화동,287,4,3,82.10,전세,신규,202504,"18,000",연립

In [11]:
# 쉼표 제거 및 문자열을 정수로 변환
jeonse_df["price"] = (
    jeonse_df["price"]
    .astype(str) # 문자열로 변환 (안전)
    .str.replace(",", "") # 쉼표 제거
    .astype(int) # 정수형으로 변환
    * 10000 # 만원 → 원 변환
)

In [12]:
# 변환된 price 컬럼 확인
jeonse_df[["price"]].head()

       price
0   67000000
1  220000000
2  425000000
3   56000000
4  180000000

In [13]:
# price 컬럼의 값을 쉼표가 포함된 문자열로 변환
jeonse_df["price"] = jeonse_df["price"].apply(lambda x: format(x, ","))
jeonse_df.head()

,address,bun,ji,floor,area,rent_type,contract_type,contract_year_month,price,housing_type
0,인천광역시 서구 석남동,481,2,4,39.92,전세,신규,202504,"67,000,000",다세대
1,서울특별시 서대문구 북가좌동,382,1,3,63.06,전세,신규,202504,"220,000,000",다세대
2,서울특별시 강남구 개포동,1205,3,4,69.22,전세,신규,202504,"425,000,000",다세대
3,인천광역시 미추홀구 주안동,631,6,3,35.94,전세,신규,202504,"56,000,000",연립다세대
4,서울특별시 중랑구 중화동,287,4,3,82.10,전세,신규,202504,"180,000,000",연립

In [14]:
# 결측치 확인
missing_counts = jeonse_df.isnull().sum()
print("📌 결측치가 있는 컬럼: ", missing_counts[missing_counts > 0])

📌 결측치가 있는 컬럼:  Series([], dtype: int64)

In [15]:
# 전체 중복된 행의 수 확인
duplicate_count = jeonse_df.duplicated().sum()
print(f"📌 중복된 행의 수: {duplicate_count}")

📌 중복된 행의 수: 284

In [16]:
# 중복 제거 (기본: 모든 열 기준, keep='first')
jeonse_df = jeonse_df.drop_duplicates().reset_index(drop=True)

In [17]:
# 전체 행의 수 확인
len(jeonse_df)

4473

In [18]:
# INSERT 구문 생성
insert_header = """INSERT INTO transaction_jeonse_rowhouse (address, bun, ji, floor, area, contract_year_month, price, housing_type, created_at, updated_at)
VALUES """

In [19]:
# 행별로 SQL 값 문자열 생성
values = []

In [20]:
# 각 행을 values 리스트에 추가
for _, row in jeonse_df.iterrows():
    values.append(f"('{row['address']}', '{row['bun']}', '{row['ji']}', '{row['floor']}', '{row['area']}', '{row['contract_year_month']}', '{row['price']}', '{row['housing_type']}', NOW(), NOW())")

In [21]:
# INSERT 구문 상위 5개만 출력
preview_sql = insert_header + ",\n       ".join(values[:5]) + ";"
print(preview_sql)

INSERT INTO transaction_jeonse_rowhouse (address, bun, ji, floor, area, contract_year_month, price, housing_type, created_at, updated_at)
VALUES ('인천광역시 서구 석남동', '481', '2', '4', '39.92', '202504', '67,000,000', '다세대', NOW(), NOW()),
       ('서울특별시 서대문구 북가좌동', '382', '1', '3', '63.06', '202504', '220,000,000', '다세대', NOW(), NOW()),
       ('서울특별시 강남구 개포동', '1205', '3', '4', '69.22', '202504', '425,000,000', '다세대', NOW(), NOW()),
       ('인천광역시 미추홀구 주안동', '631', '6', '3', '35.94', '202504', '56,000,000', '연립다세대', NOW(), NOW()),
       ('서울특별시 중랑구 중화동', '287', '4', '3', '82.1', '202504', '180,000,000', '연립', NOW(), NOW());

In [22]:
# INSERT 구문 조립
insert_sql = insert_header + ",\n       ".join(values) + ";"

In [23]:
# 파일 저장
file_name = "V57__insert_transaction_jeonse_rowhouse_202504.sql"

with open(file_name, "w", encoding="utf-8") as f:
    f.write(insert_sql)

print(f"{file_name} 파일이 생성되었습니다.")

V57__insert_transaction_jeonse_rowhouse_202504.sql 파일이 생성되었습니다.