In [1]:
# 데이터 불러오기
import pandas as pd

file_path = "/content/drive/MyDrive/JeonseGuard/실거래가/전월세/아파트/202501_아파트_전세_실거래가.csv" # CSV 파일 경로 지정
df = pd.read_csv(file_path, encoding='cp949') # CP949 인코딩

In [2]:
# 상위 5개 확인
df.head()

,NO,시군구,번지,본번,부번,단지명,전월세구분,전용면적(㎡),계약년월,계약일,...,월세금(만원),층,건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,1,경상남도 창원시 진해구 용원동,1337-3,1337,3,부산신항사랑으로부영5단지,전세,84.9933,202501,31,...,0,11,2019,신항5로 43,202502~202602,갱신,-,"12,582",0.0,아파트
1,2,경상남도 창원시 진해구 용원동,1338,1338,0,부산신항사랑으로부영6단지,전세,84.9933,202501,31,...,0,3,2019,신항5로 56,202503~202603,갱신,-,"12,582",0.0,아파트
2,3,경상남도 창원시 진해구 용원동,1338,1338,0,부산신항사랑으로부영6단지,전세,84.9933,202501,31,...,0,8,2019,신항5로 56,202502~202602,갱신,-,"12,582",0.0,아파트
3,4,전북특별자치도 전주시 덕진구 송천동2가,1342,1342,0,에코시티데시앙네스트3블럭,월세,75.8452,202501,31,...,32,2,2020,세병로 90,202503~202703,갱신,-,"14,029",32.0,아파트
4,5,충청남도 천안시 서북구 두정동,2078,2078,0,두정역효성해링턴플레이스,전세,59.8600,202501,31,...,0,28,2020,봉정로 324,202503~202703,신규,-,NaN,NaN,아파트

In [3]:
# 컬럼명 확인
print(df.columns)

Index(['NO', '시군구', '번지', '본번', '부번', '단지명', '전월세구분', '전용면적(㎡)', '계약년월', '계약일',
       '보증금(만원)', '월세금(만원)', '층', '건축년도', '도로명', '계약기간', '계약구분', '갱신요구권 사용',
       '종전계약 보증금(만원)', '종전계약 월세(만원)', '주택유형'],
      dtype='object')

In [4]:
# 특정 컬럼 값만 확인
df["보증금(만원)"].head()

0    12,833
1    12,833
2    12,833
3    14,302
4    26,000
Name: 보증금(만원), dtype: object

In [5]:
# 전세만 필터링
jeonse_df = df[df["전월세구분"] == "전세"]
jeonse_df.head()

,NO,시군구,번지,본번,부번,단지명,전월세구분,전용면적(㎡),계약년월,계약일,...,월세금(만원),층,건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,1,경상남도 창원시 진해구 용원동,1337-3,1337,3,부산신항사랑으로부영5단지,전세,84.9933,202501,31,...,0,11,2019,신항5로 43,202502~202602,갱신,-,"12,582",0.0,아파트
1,2,경상남도 창원시 진해구 용원동,1338,1338,0,부산신항사랑으로부영6단지,전세,84.9933,202501,31,...,0,3,2019,신항5로 56,202503~202603,갱신,-,"12,582",0.0,아파트
2,3,경상남도 창원시 진해구 용원동,1338,1338,0,부산신항사랑으로부영6단지,전세,84.9933,202501,31,...,0,8,2019,신항5로 56,202502~202602,갱신,-,"12,582",0.0,아파트
4,5,충청남도 천안시 서북구 두정동,2078,2078,0,두정역효성해링턴플레이스,전세,59.8600,202501,31,...,0,28,2020,봉정로 324,202503~202703,신규,-,NaN,NaN,아파트
5,6,경기도 용인시 처인구 포곡읍 둔전리,449,449,0,용인포곡삼성쉐르빌,전세,115.4429,202501,31,...,0,9,2012,포곡로 159,202502~202602,신규,-,NaN,NaN,아파트

In [6]:
# 신규만 필터링
jeonse_df = df[df["계약구분"] == "신규"]
jeonse_df.head()

,NO,시군구,번지,본번,부번,단지명,전월세구분,전용면적(㎡),계약년월,계약일,...,월세금(만원),층,건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
4,5,충청남도 천안시 서북구 두정동,2078,2078,0,두정역효성해링턴플레이스,전세,59.8600,202501,31,...,0,28,2020,봉정로 324,202503~202703,신규,-,NaN,NaN,아파트
5,6,경기도 용인시 처인구 포곡읍 둔전리,449,449,0,용인포곡삼성쉐르빌,전세,115.4429,202501,31,...,0,9,2012,포곡로 159,202502~202602,신규,-,NaN,NaN,아파트
6,7,충청남도 천안시 서북구 두정동,2078,2078,0,두정역효성해링턴플레이스,전세,59.9200,202501,31,...,0,8,2020,봉정로 324,202503~202703,신규,-,NaN,NaN,아파트
8,9,서울특별시 용산구 후암동,244-90,244,90,명남아띠팰리스,전세,68.6100,202501,31,...,0,5,2006,후암로16나길 20,202501~202901,신규,-,NaN,NaN,아파트
9,10,전북특별자치도 전주시 덕진구 송천동2가,1342,1342,0,에코시티데시앙네스트3블럭,월세,75.8452,202501,31,...,22,27,2020,세병로 90,202503~202703,신규,-,NaN,NaN,아파트

In [7]:
# 변경 매핑 딕셔너리 정의
renamed_columns = {
    "시군구": "address",
    "본번": "bun",
    "부번": "ji",
    "층": "floor",
    "전용면적(㎡)": "area",
    "전월세구분": "rent_type",
    "계약구분": "contract_type",
    "계약년월": "contract_year_month",
    "보증금(만원)": "price",
    "주택유형": "housing_type"
}

In [8]:
# 매핑에 해당하는 컬럼만 필터링
df = df.rename(columns=renamed_columns)
changed_df = df[list(renamed_columns.values())]
changed_df.head()

,address,bun,ji,floor,area,rent_type,contract_type,contract_year_month,price,housing_type
0,경상남도 창원시 진해구 용원동,1337,3,11,84.9933,전세,갱신,202501,"12,833",아파트
1,경상남도 창원시 진해구 용원동,1338,0,3,84.9933,전세,갱신,202501,"12,833",아파트
2,경상남도 창원시 진해구 용원동,1338,0,8,84.9933,전세,갱신,202501,"12,833",아파트
3,전북특별자치도 전주시 덕진구 송천동2가,1342,0,2,75.8452,월세,갱신,202501,"14,302",아파트
4,충청남도 천안시 서북구 두정동,2078,0,28,59.8600,전세,신규,202501,"26,000",아파트

In [9]:
# rent_type 컬럼에서 "전세"만 필터링
jeonse_df = changed_df[changed_df["rent_type"] == "전세"].reset_index(drop=True)
jeonse_df.head()

,address,bun,ji,floor,area,rent_type,contract_type,contract_year_month,price,housing_type
0,경상남도 창원시 진해구 용원동,1337,3,11,84.9933,전세,갱신,202501,"12,833",아파트
1,경상남도 창원시 진해구 용원동,1338,0,3,84.9933,전세,갱신,202501,"12,833",아파트
2,경상남도 창원시 진해구 용원동,1338,0,8,84.9933,전세,갱신,202501,"12,833",아파트
3,충청남도 천안시 서북구 두정동,2078,0,28,59.8600,전세,신규,202501,"26,000",아파트
4,경기도 용인시 처인구 포곡읍 둔전리,449,0,9,115.4429,전세,신규,202501,"32,000",아파트

In [10]:
# contract_type 컬럼에서 "신규"만 필터링
jeonse_df = jeonse_df[jeonse_df["contract_type"] == "신규"].reset_index(drop=True)
jeonse_df.head()

,address,bun,ji,floor,area,rent_type,contract_type,contract_year_month,price,housing_type
0,충청남도 천안시 서북구 두정동,2078,0,28,59.8600,전세,신규,202501,"26,000",아파트
1,경기도 용인시 처인구 포곡읍 둔전리,449,0,9,115.4429,전세,신규,202501,"32,000",아파트
2,충청남도 천안시 서북구 두정동,2078,0,8,59.9200,전세,신규,202501,"26,000",아파트
3,서울특별시 용산구 후암동,244,90,5,68.6100,전세,신규,202501,"23,000",아파트
4,경상북도 포항시 남구 연일읍 유강리,594,3,7,121.2300,전세,신규,202501,"24,000",아파트

In [11]:
# 쉼표 제거 및 문자열을 정수로 변환
jeonse_df["price"] = (
    jeonse_df["price"]
    .astype(str) # 문자열로 변환 (안전)
    .str.replace(",", "") # 쉼표 제거
    .astype(int) # 정수형으로 변환
    * 10000 # 만원 → 원 변환
)

In [12]:
# 변환된 price 컬럼 확인
print(jeonse_df[["price"]].head())

       price
0  260000000
1  320000000
2  260000000
3  230000000
4  240000000

In [13]:
# price 컬럼의 값을 쉼표가 포함된 문자열로 변환
jeonse_df["price"] = jeonse_df["price"].apply(lambda x: format(x, ","))
jeonse_df.head()

,address,bun,ji,floor,area,rent_type,contract_type,contract_year_month,price,housing_type
0,충청남도 천안시 서북구 두정동,2078,0,28,59.8600,전세,신규,202501,"260,000,000",아파트
1,경기도 용인시 처인구 포곡읍 둔전리,449,0,9,115.4429,전세,신규,202501,"320,000,000",아파트
2,충청남도 천안시 서북구 두정동,2078,0,8,59.9200,전세,신규,202501,"260,000,000",아파트
3,서울특별시 용산구 후암동,244,90,5,68.6100,전세,신규,202501,"230,000,000",아파트
4,경상북도 포항시 남구 연일읍 유강리,594,3,7,121.2300,전세,신규,202501,"240,000,000",아파트

In [14]:
# 결측치 확인
missing_counts = jeonse_df.isnull().sum()
print("📌 결측치가 있는 컬럼: ", missing_counts[missing_counts > 0])

📌 결측치가 있는 컬럼:  Series([], dtype: int64)

In [15]:
# 전체 중복된 행의 수 확인
duplicate_count = jeonse_df.duplicated().sum()
print(f"📌 중복된 행의 수: {duplicate_count}")

📌 중복된 행의 수: 3731

In [16]:
# 중복 제거 (기본: 모든 열 기준, keep='first')
jeonse_df = jeonse_df.drop_duplicates().reset_index(drop=True)

In [17]:
# 전체 행의 수 확인
len(jeonse_df)

27404

In [18]:
# INSERT 구문 생성
insert_header = """INSERT INTO transaction_jeonse_apartment (address, bun, ji, floor, area, contract_year_month, price, housing_type, created_at, updated_at)
VALUES """

In [19]:
# 행별로 SQL 값 문자열 생성
values = []

In [20]:
# 각 행을 values 리스트에 추가
for _, row in jeonse_df.iterrows():
    values.append(f"('{row['address']}', '{row['bun']}', '{row['ji']}', '{row['floor']}', '{row['area']}', '{row['contract_year_month']}', '{row['price']}', '{row['housing_type']}', NOW(), NOW())")

In [21]:
# INSERT 구문 상위 5개만 출력
preview_sql = insert_header + ",\n       ".join(values[:5]) + ";"
print(preview_sql)

INSERT INTO transaction_jeonse_apartment (address, bun, ji, floor, area, contract_year_month, price, housing_type, created_at, updated_at)
VALUES ('충청남도 천안시 서북구 두정동', '2078', '0', '28', '59.86', '202501', '260,000,000', '아파트', NOW(), NOW()),
       ('경기도 용인시 처인구 포곡읍 둔전리', '449', '0', '9', '115.4429', '202501', '320,000,000', '아파트', NOW(), NOW()),
       ('충청남도 천안시 서북구 두정동', '2078', '0', '8', '59.92', '202501', '260,000,000', '아파트', NOW(), NOW()),
       ('서울특별시 용산구 후암동', '244', '90', '5', '68.61', '202501', '230,000,000', '아파트', NOW(), NOW()),
       ('경상북도 포항시 남구 연일읍 유강리', '594', '3', '7', '121.23', '202501', '240,000,000', '아파트', NOW(), NOW());

In [22]:
# INSERT 구문 조립
insert_sql = insert_header + ",\n       ".join(values) + ";"

In [23]:
# 파일 저장
file_name = "V46__insert_transaction_jeonse_apartment_202501.sql"

with open(file_name, "w", encoding="utf-8") as f:
    f.write(insert_sql)

print(f"{file_name} 파일이 생성되었습니다.")

V46__insert_transaction_jeonse_apartment_202501.sql 파일이 생성되었습니다.