In [1]:
# 데이터 불러오기
import pandas as pd

file_path = "/content/drive/MyDrive/JeonseGuard/실거래가/전월세/연립다세대/202501_연립다세대_전세_실거래가.csv" # CSV 파일 경로 지정
df = pd.read_csv(file_path, encoding='cp949') # CP949 인코딩

In [2]:
# 상위 5개 확인
df.head()

,NO,시군구,번지,본번,부번,건물명,전월세구분,전용면적(㎡),계약년월,계약일,...,월세금(만원),층,건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
0,1,서울특별시 강남구 개포동,1250-6,1250,6,에치클래식,월세,45.41,202501,31,...,110,2,2013,개포로17길 20,202502~202701,갱신,-,"2,000",105,다세대
1,2,서울특별시 강동구 천호동,167-17,167,17,다성이즈빌(167-17),월세,21.27,202501,31,...,13,10,2018,진황도로29길 44,202503~202703,신규,-,NaN,NaN,다세대
2,3,서울특별시 강동구 천호동,167-97,167,97,다성이즈빌(167-97),전세,18.13,202501,31,...,0,12,2017,성안로27길 57-18,202501~202601,갱신,-,"24,150",33,다세대
3,4,서울특별시 관악구 신림동,1415-3,1415,3,아이파크,월세,25.04,202501,31,...,20,8,2015,신림로70길 77,202502~202702,신규,-,NaN,NaN,다세대
4,5,서울특별시 관악구 신림동,1474-2,1474,2,주원,월세,12.70,202501,31,...,46,7,2013,난곡로63길 8,202501~202701,신규,-,NaN,NaN,다세대

In [3]:
# 컬럼명 확인
print(df.columns)

Index(['NO', '시군구', '번지', '본번', '부번', '건물명', '전월세구분', '전용면적(㎡)', '계약년월', '계약일',
       '보증금(만원)', '월세금(만원)', '층', '건축년도', '도로명', '계약기간', '계약구분', '갱신요구권 사용',
       '종전계약 보증금(만원)', '종전계약 월세(만원)', '주택유형'],
      dtype='object')

In [4]:
# 특정 컬럼 값만 확인
df["보증금(만원)"].head()

0     2,000
1    20,500
2    17,300
3    20,000
4     2,000
Name: 보증금(만원), dtype: object

In [5]:
# 전세만 필터링
jeonse_df = df[df["전월세구분"] == "전세"]
jeonse_df.head()

,NO,시군구,번지,본번,부번,건물명,전월세구분,전용면적(㎡),계약년월,계약일,...,월세금(만원),층,건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원),주택유형
2,3,서울특별시 강동구 천호동,167-97,167,97,다성이즈빌(167-97),전세,18.13,202501,31,...,0,12,2017,성안로27길 57-18,202501~202601,갱신,-,"24,150",33,다세대
7,8,서울특별시 강동구 천호동,309-11,309,11,삼성베스트빌,전세,42.25,202501,31,...,0,3,2016,천중로15가길 1-11,202502~202702,갱신,-,"32,475",0,다세대
8,9,서울특별시 송파구 송파동,24-8,24,8,(24-8),전세,41.96,202501,31,...,0,3,2004,송파대로44길 29,202503~202703,신규,-,NaN,NaN,다세대
9,10,부산광역시 수영구 광안동,88-24,88,24,트라움하우스14차,전세,23.55,202501,31,...,0,2,2017,수영로674번길 17-3,202503~202703,신규,-,NaN,NaN,다세대
11,12,부산광역시 수영구 광안동,155-6,155,6,트라움하우스13차,전세,22.38,202501,31,...,0,3,2017,수영로594번길 76,202503~202703,신규,-,NaN,NaN,다세대

In [6]:
# 변경 매핑 딕셔너리 정의
renamed_columns = {
    "시군구": "address",
    "본번": "bun",
    "부번": "ji",
    "층": "floor",
    "전월세구분": "rent_type",
    "계약년월": "contract_year_month",
    "보증금(만원)": "price",
    "주택유형": "housing_type"
}

In [7]:
# 매핑에 해당하는 컬럼만 필터링
df = df.rename(columns=renamed_columns)
changed_df = df[list(renamed_columns.values())]
changed_df.head()

,address,bun,ji,floor,rent_type,contract_year_month,price,housing_type
0,서울특별시 강남구 개포동,1250,6,2,월세,202501,"2,000",다세대
1,서울특별시 강동구 천호동,167,17,10,월세,202501,"20,500",다세대
2,서울특별시 강동구 천호동,167,97,12,전세,202501,"17,300",다세대
3,서울특별시 관악구 신림동,1415,3,8,월세,202501,"20,000",다세대
4,서울특별시 관악구 신림동,1474,2,7,월세,202501,"2,000",다세대

In [8]:
# rent_type 컬럼에서 "전세"만 필터링
jeonse_df = changed_df[changed_df["rent_type"] == "전세"].reset_index(drop=True)
jeonse_df.head()

,address,bun,ji,floor,rent_type,contract_year_month,price,housing_type
0,서울특별시 강동구 천호동,167,97,12,전세,202501,"17,300",다세대
1,서울특별시 강동구 천호동,309,11,3,전세,202501,"33,975",다세대
2,서울특별시 송파구 송파동,24,8,3,전세,202501,"21,980",다세대
3,부산광역시 수영구 광안동,88,24,2,전세,202501,"9,000",다세대
4,부산광역시 수영구 광안동,155,6,3,전세,202501,"10,000",다세대

In [9]:
# 쉼표 제거 및 문자열을 정수로 변환
jeonse_df["price"] = (
    jeonse_df["price"]
    .astype(str) # 문자열로 변환 (안전)
    .str.replace(",", "") # 쉼표 제거
    .astype(int) # 정수형으로 변환
    * 10000 # 만원 → 원 변환
)

In [10]:
# 변환된 price 컬럼 확인
jeonse_df[["price"]].head()

       price
0  173000000
1  339750000
2  219800000
3   90000000
4  100000000

In [11]:
# price 컬럼의 값을 쉼표가 포함된 문자열로 변환
jeonse_df["price"] = jeonse_df["price"].apply(lambda x: format(x, ","))
jeonse_df.head()

,address,bun,ji,floor,rent_type,contract_year_month,price,housing_type
0,서울특별시 강동구 천호동,167,97,12,전세,202501,"173,000,000",다세대
1,서울특별시 강동구 천호동,309,11,3,전세,202501,"339,750,000",다세대
2,서울특별시 송파구 송파동,24,8,3,전세,202501,"219,800,000",다세대
3,부산광역시 수영구 광안동,88,24,2,전세,202501,"90,000,000",다세대
4,부산광역시 수영구 광안동,155,6,3,전세,202501,"100,000,000",다세대

In [12]:
# 결측치 확인
missing_counts = jeonse_df.isnull().sum()
print("📌 결측치가 있는 컬럼: ", missing_counts[missing_counts > 0])

📌 결측치가 있는 컬럼:  Series([], dtype: int64)

In [13]:
# 전체 중복된 행의 수 확인
duplicate_count = jeonse_df.duplicated().sum()
print(f"📌 중복된 행의 수: {duplicate_count}")

📌 중복된 행의 수: 615

In [14]:
# 중복 제거 (기본: 모든 열 기준, keep='first')
jeonse_df = jeonse_df.drop_duplicates().reset_index(drop=True)

In [15]:
# INSERT 구문 생성
insert_header = """INSERT INTO jeonse_transaction_rowhouse (address, bun, ji, floor, rent_type, contract_year_month, price, housing_type, created_at, updated_at)
VALUES """

In [16]:
# 행별로 SQL 값 문자열 생성
values = []

In [17]:
# 각 행을 values 리스트에 추가
for _, row in jeonse_df.iterrows():
    values.append(f"('{row['address']}', '{row['bun']}', '{row['ji']}', '{row['floor']}', '{row['rent_type']}', '{row['contract_year_month']}', '{row['price']}', '{row['housing_type']}', NOW(), NOW())")

In [18]:
# INSERT 구문 상위 5개만 출력
preview_sql = insert_header + ",\n       ".join(values[:5]) + ";"
print(preview_sql)

INSERT INTO jeonse_transaction_rowhouse (address, bun, ji, floor, rent_type, contract_year_month, price, housing_type, created_at, updated_at)
VALUES ('서울특별시 강동구 천호동', '167', '97', '12', '전세', '202501', '173,000,000', '다세대', NOW(), NOW()),
       ('서울특별시 강동구 천호동', '309', '11', '3', '전세', '202501', '339,750,000', '다세대', NOW(), NOW()),
       ('서울특별시 송파구 송파동', '24', '8', '3', '전세', '202501', '219,800,000', '다세대', NOW(), NOW()),
       ('부산광역시 수영구 광안동', '88', '24', '2', '전세', '202501', '90,000,000', '다세대', NOW(), NOW()),
       ('부산광역시 수영구 광안동', '155', '6', '3', '전세', '202501', '100,000,000', '다세대', NOW(), NOW());

In [19]:
# INSERT 구문 조립
insert_sql = insert_header + ",\n       ".join(values) + ";"

In [20]:
# 파일 저장
file_name = "V30__insert_jeonse_transaction_rowhouse_202501.sql"

with open(file_name, "w", encoding="utf-8") as f:
    f.write(insert_sql)

print(f"{file_name} 파일이 생성되었습니다.")

V30__insert_jeonse_transaction_rowhouse_202501.sql 파일이 생성되었습니다.