In [1]:
# 데이터 불러오기
import pandas as pd

file_path = "/content/drive/MyDrive/JeonseGuard/실거래가/전월세/오피스텔/202501_오피스텔_전세_실거래가.csv" # CSV 파일 경로 지정
df = pd.read_csv(file_path, encoding='cp949') # CP949 인코딩

In [2]:
# 상위 5개 확인
df.head()

,NO,시군구,번지,본번,부번,단지명,전월세구분,전용면적(㎡),계약년월,계약일,보증금(만원),월세금(만원),층,건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원)
0,1,부산광역시 서구 부민동2가,9-13,9,13,한누리타워,전세,26.71,202501,31,"6,000",0,6,2017.0,임시수도기념로 21-27,202502~202802,신규,-,NaN,NaN
1,2,부산광역시 서구 부민동2가,9-13,9,13,한누리타워,월세,26.71,202501,31,"1,000",37,5,2017.0,임시수도기념로 21-27,202502~202602,신규,-,NaN,NaN
2,3,부산광역시 서구 부민동2가,9-13,9,13,한누리타워,월세,28.27,202501,31,"6,000",10,4,2017.0,임시수도기념로 21-27,202502~202602,갱신,-,"6,000",8.0
3,4,부산광역시 서구 토성동1가,33-8,33,8,트레저,월세,23.80,202501,31,"6,600",18,4,2022.0,구덕로124번길 49,202503~202703,신규,-,NaN,NaN
4,5,인천광역시 서구 청라동,167-17,167,17,딜라이트타워2,전세,32.04,202501,31,"8,600",0,12,2013.0,청라에메랄드로 84,202502~202702,신규,-,NaN,NaN

In [3]:
# 컬럼명 확인
print(df.columns)

Index(['NO', '시군구', '번지', '본번', '부번', '단지명', '전월세구분', '전용면적(㎡)', '계약년월', '계약일',
       '보증금(만원)', '월세금(만원)', '층', '건축년도', '도로명', '계약기간', '계약구분', '갱신요구권 사용',
       '종전계약 보증금(만원)', '종전계약 월세(만원)'],
      dtype='object')

In [4]:
# 특정 컬럼 값만 확인
df["보증금(만원)"].head()

0    6,000
1    1,000
2    6,000
3    6,600
4    8,600
Name: 보증금(만원), dtype: object

In [5]:
# 전세만 필터링
jeonse_df = df[df["전월세구분"] == "전세"]
jeonse_df.head()

,NO,시군구,번지,본번,부번,단지명,전월세구분,전용면적(㎡),계약년월,계약일,보증금(만원),월세금(만원),층,건축년도,도로명,계약기간,계약구분,갱신요구권 사용,종전계약 보증금(만원),종전계약 월세(만원)
0,1,부산광역시 서구 부민동2가,9-13,9,13,한누리타워,전세,26.71,202501,31,"6,000",0,6,2017.0,임시수도기념로 21-27,202502~202802,신규,-,NaN,NaN
4,5,인천광역시 서구 청라동,167-17,167,17,딜라이트타워2,전세,32.04,202501,31,"8,600",0,12,2013.0,청라에메랄드로 84,202502~202702,신규,-,NaN,NaN
14,15,서울특별시 영등포구 당산동2가,159-3,159,3,우성하임,전세,63.42,202501,31,"16,500",0,2,2017.0,선유동1로 24-18,202503~202703,신규,-,NaN,NaN
15,16,광주광역시 광산구 쌍암동,687-2,687,2,첨단 중해마루힐 2차 주상복합,전세,84.92,202501,31,"18,000",0,26,2023.0,첨단중앙로182번길 76,202503~202703,신규,-,NaN,NaN
16,17,광주광역시 광산구 쌍암동,657-5,657,5,첨단 한국아델리움 메트로시티,전세,50.98,202501,31,"17,500",0,12,2022.0,임방울대로 773,202503~202703,신규,-,NaN,NaN

In [6]:
# 주택유형 컬럼 추가
df["주택유형"] = "오피스텔"

In [7]:
# 변경 매핑 딕셔너리 정의
renamed_columns = {
    "시군구": "address",
    "본번": "bun",
    "부번": "ji",
    "층": "floor",
    "전월세구분": "rent_type",
    "계약년월": "contract_year_month",
    "보증금(만원)": "price",
    "주택유형": "housing_type"
}

In [8]:
# 매핑에 해당하는 컬럼만 필터링
df = df.rename(columns=renamed_columns)
changed_df = df[list(renamed_columns.values())]
changed_df.head()

,address,bun,ji,floor,rent_type,contract_year_month,price,housing_type
0,부산광역시 서구 부민동2가,9,13,6,전세,202501,"6,000",오피스텔
1,부산광역시 서구 부민동2가,9,13,5,월세,202501,"1,000",오피스텔
2,부산광역시 서구 부민동2가,9,13,4,월세,202501,"6,000",오피스텔
3,부산광역시 서구 토성동1가,33,8,4,월세,202501,"6,600",오피스텔
4,인천광역시 서구 청라동,167,17,12,전세,202501,"8,600",오피스텔

In [9]:
# rent_type 컬럼에서 "전세"만 필터링
jeonse_df = changed_df[changed_df["rent_type"] == "전세"].reset_index(drop=True)
jeonse_df.head()

,address,bun,ji,floor,rent_type,contract_year_month,price,housing_type
0,부산광역시 서구 부민동2가,9,13,6,전세,202501,"6,000",오피스텔
1,인천광역시 서구 청라동,167,17,12,전세,202501,"8,600",오피스텔
2,서울특별시 영등포구 당산동2가,159,3,2,전세,202501,"16,500",오피스텔
3,광주광역시 광산구 쌍암동,687,2,26,전세,202501,"18,000",오피스텔
4,광주광역시 광산구 쌍암동,657,5,12,전세,202501,"17,500",오피스텔

In [10]:
# 쉼표 제거 및 문자열을 정수로 변환
jeonse_df["price"] = (
    jeonse_df["price"]
    .astype(str) # 문자열로 변환 (안전)
    .str.replace(",", "") # 쉼표 제거
    .astype(int) # 정수형으로 변환
    * 10000 # 만원 → 원 변환
)

In [11]:
# 변환된 price 컬럼 확인
jeonse_df[["price"]].head()

       price
0   60000000
1   86000000
2  165000000
3  180000000
4  175000000

In [12]:
# price 컬럼의 값을 쉼표가 포함된 문자열로 변환
jeonse_df["price"] = jeonse_df["price"].apply(lambda x: format(x, ","))
jeonse_df.head()

,address,bun,ji,floor,rent_type,contract_year_month,price,housing_type
0,부산광역시 서구 부민동2가,9,13,6,전세,202501,"60,000,000",오피스텔
1,인천광역시 서구 청라동,167,17,12,전세,202501,"86,000,000",오피스텔
2,서울특별시 영등포구 당산동2가,159,3,2,전세,202501,"165,000,000",오피스텔
3,광주광역시 광산구 쌍암동,687,2,26,전세,202501,"180,000,000",오피스텔
4,광주광역시 광산구 쌍암동,657,5,12,전세,202501,"175,000,000",오피스텔

In [13]:
# 결측치 확인
missing_counts = jeonse_df.isnull().sum()
print("📌 결측치가 있는 컬럼: ", missing_counts[missing_counts > 0])

📌 결측치가 있는 컬럼:  Series([], dtype: int64)

In [14]:
# 전체 중복된 행의 수 확인
duplicate_count = jeonse_df.duplicated().sum()
print(f"📌 중복된 행의 수: {duplicate_count}")

📌 중복된 행의 수: 209

In [15]:
# 중복 제거 (기본: 모든 열 기준, keep='first')
jeonse_df = jeonse_df.drop_duplicates().reset_index(drop=True)

In [16]:
# INSERT 구문 생성
insert_header = """INSERT INTO jeonse_transaction_officetel (address, bun, ji, floor, rent_type, contract_year_month, price, housing_type, created_at, updated_at)
VALUES """

In [17]:
# 행별로 SQL 값 문자열 생성
values = []

In [18]:
# 각 행을 values 리스트에 추가
for _, row in jeonse_df.iterrows():
    values.append(f"('{row['address']}', '{row['bun']}', '{row['ji']}', '{row['floor']}', '{row['rent_type']}', '{row['contract_year_month']}', '{row['price']}', '{row['housing_type']}', NOW(), NOW())")

In [19]:
# INSERT 구문 상위 5개만 출력
preview_sql = insert_header + ",\n       ".join(values[:5]) + ";"
print(preview_sql)

INSERT INTO jeonse_transaction_officetel (address, bun, ji, floor, rent_type, contract_year_month, price, housing_type, created_at, updated_at)
VALUES ('부산광역시 서구 부민동2가', '9', '13', '6', '전세', '202501', '60,000,000', '오피스텔', NOW(), NOW()),
       ('인천광역시 서구 청라동', '167', '17', '12', '전세', '202501', '86,000,000', '오피스텔', NOW(), NOW()),
       ('서울특별시 영등포구 당산동2가', '159', '3', '2', '전세', '202501', '165,000,000', '오피스텔', NOW(), NOW()),
       ('광주광역시 광산구 쌍암동', '687', '2', '26', '전세', '202501', '180,000,000', '오피스텔', NOW(), NOW()),
       ('광주광역시 광산구 쌍암동', '657', '5', '12', '전세', '202501', '175,000,000', '오피스텔', NOW(), NOW());

In [20]:
# INSERT 구문 조립
insert_sql = insert_header + ",\n       ".join(values) + ";"

In [21]:
# 파일 저장
file_name = "V25__insert_jeonse_transaction_officetel_202501.sql"

with open(file_name, "w", encoding="utf-8") as f:
    f.write(insert_sql)

print(f"{file_name} 파일이 생성되었습니다.")

V25__insert_jeonse_transaction_officetel_202501.sql 파일이 생성되었습니다.